/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.negod.negoddeployer.jframes;

import org.negod.negoddeployer.controller.Application;
import org.negod.negoddeployer.enums.EventTypes;
import static org.negod.negoddeployer.enums.EventTypes.CHANGE_PROGRESS_BAR;
import static org.negod.negoddeployer.enums.EventTypes.CHANGE_PROGRESS_TEXT;
import org.negod.negoddeployer.interfaces.EventObserver;

/**
 *
 * @author jojoha
 */
public class TaskProgressBar extends javax.swing.JPanel implements EventObserver {

    /**
     * Creates new form TaskProgressBar
     */
    public TaskProgressBar() {
        initComponents();
        jLabel1.setText("");
    }

    @Override
    public void update(EventTypes eventType, Object data) {
        switch (eventType) {
            case CHANGE_PROGRESS_BAR:
                setProgress((Integer) data);
                break;
            case CHANGE_PROGRESS_TEXT:
                setText((String) data);
                break;
            case FILE_UNZIPPED_FAILURE:
                setText((String) data);
                break;
        }
    }

    @Override
    public void registerAsObserver() {
        Application.getEvents().addObserver(this);
    }

    public void setProgress(int value) {
        jProgressBar1.setValue(value);
    }

    public void setText(String text) {
        jLabel1.setText(text);
    }

    public void setMinValue(int vaule) {
    }

    public void setMaxValue(int vaule) {
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
